-- ==============================================================================
-- 00_BOOTSTRAP.SQL — Idempotent Account & Database Setup for ARGUS
-- ==============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Resource Monitor (Cost Guardrail)
CREATE OR REPLACE RESOURCE MONITOR ARGUS_RM
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50  PERCENT DO NOTIFY
    ON 75  PERCENT DO NOTIFY
    ON 90  PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- 2. Single XSMALL Warehouse
CREATE WAREHOUSE IF NOT EXISTS ARGUS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  RESOURCE_MONITOR = ARGUS_RM
  COMMENT = 'ARGUS single X-Small warehouse for vertical slice';

USE WAREHOUSE ARGUS_WH;

-- 3. Database
CREATE DATABASE IF NOT EXISTS ARGUS;
USE DATABASE ARGUS;

-- 4. Schemas
CREATE SCHEMA IF NOT EXISTS ARGUS.RAW;
CREATE SCHEMA IF NOT EXISTS ARGUS.CURATED;
CREATE SCHEMA IF NOT EXISTS ARGUS.DOC;
CREATE SCHEMA IF NOT EXISTS ARGUS.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS ARGUS.SEARCH;
CREATE SCHEMA IF NOT EXISTS ARGUS.AGENT;
CREATE SCHEMA IF NOT EXISTS ARGUS.AUDIT;
CREATE SCHEMA IF NOT EXISTS ARGUS.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS ARGUS.APP;

-- 5. Roles & RBAC Setup
CREATE ROLE IF NOT EXISTS ARGUS_ADMIN;
CREATE ROLE IF NOT EXISTS ARGUS_FRAUD_ANALYST;
CREATE ROLE IF NOT EXISTS ARGUS_COMPLIANCE_OFFICER;
CREATE ROLE IF NOT EXISTS ARGUS_AUDITOR;

-- Base reader / usage privileges
GRANT USAGE ON WAREHOUSE ARGUS_WH TO ROLE ARGUS_ADMIN;
GRANT USAGE ON WAREHOUSE ARGUS_WH TO ROLE ARGUS_FRAUD_ANALYST;
GRANT USAGE ON WAREHOUSE ARGUS_WH TO ROLE ARGUS_COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE ARGUS_WH TO ROLE ARGUS_AUDITOR;

GRANT ALL PRIVILEGES ON DATABASE ARGUS TO ROLE ARGUS_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ARGUS TO ROLE ARGUS_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ARGUS TO ROLE ARGUS_ADMIN;

-- Grant to current user
SET CURRENT_USER_NAME = CURRENT_USER();
GRANT ROLE ARGUS_ADMIN TO USER IDENTIFIER($CURRENT_USER_NAME);
GRANT ROLE ARGUS_FRAUD_ANALYST TO USER IDENTIFIER($CURRENT_USER_NAME);
GRANT ROLE ARGUS_COMPLIANCE_OFFICER TO USER IDENTIFIER($CURRENT_USER_NAME);
GRANT ROLE ARGUS_AUDITOR TO USER IDENTIFIER($CURRENT_USER_NAME);

SELECT 'Bootstrap completed successfully' AS STATUS;
